name: examen_sm2
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ğŸ“Š GrÃ¡ficos para dashboard
  fl_chart: ^0.66.0

  # ğŸ“¤ Exportar a CSV
  csv: ^5.0.2

  # ğŸ“¤ Exportar a Excel
  excel: ^4.0.2

  # ğŸ“ Acceso a carpetas (para guardar archivos exportados)
  path_provider: ^2.1.2

  # ğŸ¨ Para simular estilos Bootstrap
  flutter_bootstrap5: ^1.0.1 # (opcional, si quieres estilo visual mÃ¡s "bootstrap")

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
